envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: Superhero
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: shaneloewe/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bacs350-demo-app
  routes:
  - path: /
  run_command: |-
    python manage.py migrate --no-input
    python manage.py loaddata database.json
    python manage.py build database
    python manage.py createsuperuser --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Superhero
static_sites:
    - environment_slug: html
      github:
        branch: production
        deploy_on_push: true
        repo: shaneloewe/PythonWebApps
      name: urchin-app-static
      routes:
      - path: /static
      source_dir: /static