# Generated by Django 4.1.1 on 2022-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroName', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('powerLevel', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='./static/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
