# Generated by Django 4.1.1 on 2022-09-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_hero_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='powerLevel',
            new_name='origin',
        ),
    ]
