# Generated by Django 4.1.1 on 2022-10-17 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero', '0004_superhero_bleh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='bleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
