# Generated by Django 4.1.1 on 2022-10-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_alter_superhero_bleh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='bleh',
            new_name='author',
        ),
    ]
