# Generated by Django 4.1.1 on 2022-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='author',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
