# Generated by Django 4.1.1 on 2022-11-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='None', upload_to='../../media/images/'),
        ),
    ]
