# Generated by Django 4.1.1 on 2022-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_remove_superhero_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='bleh',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
