# Generated by Django 4.1 on 2022-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_alter_superhero_author_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
