# Generated by Django 4.1.1 on 2022-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='picture',
            field=models.CharField(max_length=200),
        ),
    ]
